version: "3.1"
  
services:
  mongo:
    image: mongo:latest
    container_name: mdb
    ports:
      - "27018:27017"
    volumes:
      - ./mongorestore.sh:/docker-entrypoint-initdb.d/mongorestore.sh
      - ./dump:/dump